# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Carbon Dioxide SOP
author: Brita Irving
logo: docs/IARC.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: CO2_SOP.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/britairving/Carbon_Dioxide_SOP  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  comments:
    utterances:
      repo: "britairving/Carbon_Dioxide_SOP"
# Add a bibtex file so that we can create citations

sphinx:
  config:
    bibtex_reference_style: author_year
    html_show_copyright: false

bibtex_reference_style      : author_year_round
bibtex_default_style        : myapastyle
bibtex_bibfiles             : co2_references.bib